### PR TITLE
added the contributing file

### PR DESCRIPTION
**Pull request by Sloth-Panda**
Added the contributing.md file

### CODE REVIEW

**Comment by shriyaMadan** [comment]
@Sloth-Panda at point number 8 the image isn't loading, correct it.
And the last statement-point no. 15  needs to be edited a little bit.

**Comment by Sloth-Panda** [comment]
Screenshot (33)


Hey, no.8  image is perfectly working and  made few small changes to line 15. What do you want to change from here?

**Comment by shriyaMadan** [comment]
line 15 "at times the times" edit it

**Comment by shriyaMadan** [comment]
@Sloth-Panda can you see the image isn't visible at point 8?

**Comment by shriyaMadan** [comment]
image

**Comment by shriyaMadan** [comment]
Fix this

**Comment by Sloth-Panda** [comment]
Yes, IDK why it's not showing still changing it, and also please add a level to this issue or close it with the previous one

**Pull request merged**
