### PR TITLE
Add Template for Issues

### PR DESCRIPTION
**Pull request by muthuannamalai12**
I have added an issue template for your repository. This template has four issues namely bug, documentation, feature, proposal.

### CODE REVIEW

**Comment by shriyaMadan** [comment]
@muthuannamalai12 change the PR name such PR naming won't be acceptable. Check the wiki file to see the PR naming convention. It should describe the issue solved.

**Comment by muthuannamalai12** [comment]
> @muthuannamalai12 change the PR name such PR naming won't be acceptable. Check the wiki file to see the PR naming convention. It should describe the issue solved.

I have changed it as Add Issue Template. Os that okay??@shriyaMadan

**Comment by shriyaMadan** [comment]
Pull Requests should use the present imperative present tense:  change it back to "Add Template for Issues".

**Comment by muthuannamalai12** [comment]
> Pull Requests should use the present imperative present tense:  change it back to "Add Template for Issues".

I have changed it again. Sorry for inconvenience

**Pull request merged**
