### PR TITLE
Website logo

### PR DESCRIPTION
**Pull request by Muskan10Mehta**
Website Logo added under the name Y.PNG

### CODE REVIEW

**Comment by shriyaMadan** [comment]
@Muskan10Mehta you have added your Logo to the root of the project. Kindly add it to this folder Public/Images.

**Comment by Muskan10Mehta** [comment]
Oh ok

**Comment by Muskan10Mehta** [comment]
is it okay now?

**Comment by shriyaMadan** [comment]
No @Muskan10Mehta First of all change the name from Y.png to logo.png and secondly, I cant understand the need to make so many commits added and deleted the folder again and again. 
I want you to make a new PR with a single clean commit and proper message. 
(Closing this one)

**Pull request closed without merging**
