### PR TITLE
improve readme & add links to discord & wiki

### PR DESCRIPTION
**Pull request by Sloth-Panda**
corresponds to issue -> #73

### CODE REVIEW

**Comment by shriyaMadan** [comment]
Nice work but has abrupt ending, changes needed:
1- In the ending part, it is mentioning about DWOC, though it should mention that this project is a part of DWOC and Contributions to this project are currently welcomed through DWOC
2- DWOC image size should be smaller and image should not open up as a link itself. 
3- Mention the tech stack used: Expressjs for backend and HTML, CSS, Bootstrap, Javascript for Frontend
4- mention project maintainer & mentor 
5- Feel free to contribute and then add the discord channel link

**Comment by Sloth-Panda** [comment]
okay
, few queries->
1. should the text saying what dwoc and it's image is there or that to be replaced by point 1 or be added in extra?
2. are u the only maintainer/mentor?
3.  Should i add Feel free to contribute at the dead end I mean is not it better to keep channel link inside of readme. can you explain the last point where to put "feel free...." and the discord link?

**Comment by Sloth-Panda** [comment]
checkout the PR , hope it's good now else let me know and if possible make the issue a level-3. I did contributed to one of your level-3 issues before but its not yet reflected

**Comment by shriyaMadan** [comment]
> checkout the PR , hope it's good now else let me know and if possible make the issue a level-3. I did contributed to one of your level-3 issues before but its not yet reflected

this is Level-3 only, don't see the issue's level, PR Level matters
Check the PR which isn't counted yet, if there is any label on it?

**Pull request merged**
